[package]
name = "kcci"
version = "0.1.0"
edition = "2021"
authors = ["Brian McCallister <brianm@skife.org>"]
description = "Build and query indexes of books"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = "1.9.1"
rust-bert = "0.21.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "std"]}

[dev-dependencies]
pretty_assertions = "1.3.0"
