#!/usr/bin/env python3

import click
from typing import List

import book_finder as bf

@click.group()
def cli():
    pass

@cli.command(name="basics")
@click.argument('query', nargs=-1)
def basics(query: List[str]):
    import ss_play as ss # only import if needed, long load time
    ss.play(' '.join(query))    

@cli.command()
@click.option('--author', '-a', multiple=True)
@click.option('--title', '-t')
def ol(title: str, author: List[str]):
    book = bf.openlibrary_lookup(title, author)
    click.echo(f"{book.title} by {', '.join(book.authors)}")
    click.echo("")
    click.echo(book.description)

@cli.command()
@click.option('--author', '-a', multiple=True)
@click.option('--title', '-t')
def loc(title: str, author: List[str]):
    book = bf.loc_lookup(title, author)
    click.echo(f"{book.title} by {', '.join(book.authors)}")
    click.echo("")
    click.echo(book.description)

if __name__ == '__main__':
    cli()