#!/usr/bin/env python3

import click # type: ignore
from typing import List

import kcci.book_finder as bf

@click.group()
def cli():
    pass


@cli.command(name="basics")
@click.option("--num", "-n", default=1)
@click.argument("query", nargs=-1)
def basics(num: int, query: List[str]):
    import kcci.ss_play as ss  # only import if needed, long load time

    ss.play(num, " ".join(query))


@cli.command()
@click.option("--author", "-a", multiple=True)
@click.option("--title", "-t")
def ol(title: str, author: List[str]):
    book = bf.openlibrary_lookup(title, author)
    click.echo(f"{book.title} by {', '.join(book.authors)}")
    click.echo("")
    click.echo(book.description)


@cli.command()
@click.option("--author", "-a", multiple=True)
@click.option("--title", "-t")
def loc(title: str, author: List[str]):
    book = bf.loc_lookup(title, author)
    click.echo(f"{book.title} by {', '.join(book.authors)}")
    click.echo("")
    click.echo(book.description)


if __name__ == "__main__":
    cli()
